### ISSUE TITLE
Clarify post-GCC-6 support

### ISSUE THREAD

**Issue by eyalroz** [SuperV1234/camomilla#3]
Hello Vittorio,

I've just noticed this nice project of yours. Does it support GCC versions 7, 8 and 9? Or perhaps I should say - how useful is it with those versions?

The README.md should clarify this point.

(Also it wouldn't hurt to say if the project is abandoned, done/complete, or awaiting future work when you have the time.)

**Comment by vittorioromeo** [comment]
Hello, 

I just tried it with `g++ 9` using the example in the README and it still helps a lot. I am also not actively working on this, but I am more than happy to accept/review PRs. 

Closing this issue, but feel free to re-open if you have any further question. 

Cheers!
